name: exemple1

on: push

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Dire Bonjour
              run: |
                echo 'Bonjour les AMIS'
                ls -altr
                cat README.md

            - name: Generner ASCI 
              run: cowsat -f dragon "Run for cover" >> dragon.txt
            
#          - name: Lister les fichiers
#             run: ls

 #           - name: Lire le fchier
  #            run: cat README.md
    
