name: MATRIX STRATEGY


on:
    push

jobs:
    Job1:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latset] 
                images: [hello-world, alpine]
                exclude:
                    - images : alpine
                      os: windows-latset

        runs-on: ${{ matrix.os }}
        steps:
            - name: Version
              run: docker info 
            

            - name: Run images
              run: docker run ${{ matrix.images }}