name: working with step level var

on:
    push

jobs:
    docker:
        env: 
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: siddharth1
            IAMGE_NAME: github-actions-nginx
        runs-on: ubuntu-latest
        steps:
         - name: Docker Build
           run:  echo docker build -t ${{env.CONTAINER_REGISTRY}}/$DOCKER_USERNAME/$IAMGE_NAME:latest

         - name: Docker login
           env: 
            DOCKER_PASSWORD: s3cUrePassw0rd
           run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
        
         - name: Docker Publish
           run:  echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IAMGE_NAME:latest

    deploy:
        env: 
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: siddharth1
            IAMGE_NAME: github-actions-nginx
        runs-on: ubuntu-latest
        steps:
         - name: Docker Run
           run:  echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IAMGE_NAME:latest