name: working with step level var

on:
    push

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
         - name: Docker Build
           env: 
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: siddharth1
            IAMGE_NAME: github-actions-nginx
            
           run:  docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IAMGE_NAME:latest

         - name: Docker login
           env: 
            DOCKER_USERNAME: siddharth1
            DOCKER_PASSWORD: s3cUrePassw0rd
            
           run:  docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
        
         - name: Docker Publish
           env: 
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: siddharth1
                IAMGE_NAME: github-actions-nginx
           run:  docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IAMGE_NAME:latest

    deploy:
        runs-on: ubuntu-latest
        steps:
         - name: Docker Run
           env: 
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: siddharth1
                IAMGE_NAME: github-actions-nginx
           run:  docker  run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IAMGE_NAME:latest

      
    

